# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

TEMPLATE = subdirs
CONFIG += release \
warn_on \
ordered
SUBDIRS += quazip \
  swe_171 \
  zoneinfo \
  symsolon

