# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/zoneinfo
# Target is a library:  

HEADERS += private.h \
           tzfile.h 
SOURCES += localtime.c \
           difftime.c 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
DESTDIR = output

